import type { ContextStats, RepoMeta, Report } from './types';

function line(value: string | undefined | null): string {
  return (value ?? '').replace(/\s+/g, ' ').trim();
}

/** Escape a value for direct placement inside a GFM table cell (between the `|` characters). */
function escCell(value: string | undefined | null): string {
  return line(value).replace(/\|/g, '\\|');
}

/** Escape a value for placement inside a backtick inline code span. */
function escCode(value: string | undefined | null): string {
  return line(value).replace(/`/g, '\\`');
}

function bullets(items: string[], prefix = '- '): string {
  return items.map((item) => `${prefix}${line(item)}`).join('\n');
}

export function buildOnboardingMarkdown(
  meta: RepoMeta,
  report: Report,
  stats: ContextStats | null,
  sourceUrl: string,
): string {
  const out: string[] = [];
  const generatedAt = new Date().toISOString().slice(0, 19).replace('T', ' ');

  out.push(`# OnboardPilot report — ${meta.fullName}`);
  out.push('');
  out.push(`> Generated by **OnboardPilot** on ${generatedAt} UTC.`);
  out.push(`> Source repository: ${sourceUrl}`);
  if (stats) {
    out.push(
      `> Scanned **${stats.filesInRepo}** tracked files, read **${stats.filesRead}** key files (${Math.round(
        stats.charsRead / 1024,
      )} KB), found **${stats.docsFound}** documentation files and **${stats.testFiles}** test files.`,
    );
  }
  out.push(
    '> AI-generated from the repository source. Every claim cites the file it came from so you can verify it before you trust it.',
  );
  out.push('');

  const arch = report.architecture;
  if (arch) {
    out.push('## 1. What this codebase is');
    out.push('');
    out.push(line(arch.summary));
    out.push('');
    if (arch.stack?.length) {
      out.push(`**Stack:** ${arch.stack.map(line).join(' · ')}`);
      out.push('');
    }

    out.push('## 2. Architecture map');
    out.push('');
    for (const layer of arch.layers ?? []) {
      out.push(`### ${line(layer.name)}`);
      out.push(`_${line(layer.purpose)}_`);
      out.push('');
      for (const mod of layer.modules ?? []) {
        out.push(`- **${line(mod.name)}** (\`${escCode(mod.path)}\`) — ${line(mod.responsibility)}`);
        if (mod.keyFiles?.length) {
          out.push(`  - key files: ${mod.keyFiles.map((f) => `\`${escCode(f)}\``).join(', ')}`);
        }
      }
      out.push('');
    }

    if (arch.flows?.length) {
      out.push('## 3. Important flows');
      out.push('');
      for (const flow of arch.flows) {
        out.push(`### ${line(flow.name)}`);
        out.push('');
        (flow.steps ?? []).forEach((step, index) => {
          const evidence = step.evidence?.length
            ? ` _(${step.evidence.map((f) => `\`${escCode(f)}\``).join(', ')})_`
            : '';
          out.push(`${index + 1}. **${line(step.label)}** — ${line(step.detail)}${evidence}`);
        });
        out.push('');
      }
    }

    if (arch.unknowns?.length) {
      out.push('### Honest gaps');
      out.push('');
      out.push(bullets(arch.unknowns));
      out.push('');
    }
  }

  const entries = report.entrypoints;
  if (entries) {
    out.push('## 4. How execution starts');
    out.push('');
    out.push(line(entries.summary));
    out.push('');
    for (const entry of entries.entryPoints ?? []) {
      out.push(
        `- **${line(entry.name)}** (\`${escCode(entry.path)}\`) · ${line(entry.kind)} · trigger: ${line(
          entry.trigger,
        )} — ${line(entry.description)}`,
      );
    }
    out.push('');
    if (entries.trace) {
      out.push(`### End-to-end trace: ${line(entries.trace.name)}`);
      out.push('');
      for (const step of entries.trace.steps ?? []) {
        const files = step.files?.length ? ` [${step.files.map((f) => `\`${escCode(f)}\``).join(', ')}]` : '';
        out.push(`${step.order}. **${line(step.action)}**${files} — ${line(step.note)}`);
      }
      out.push('');
    }
  }

  const conv = report.conventions;
  if (conv) {
    out.push('## 5. House rules');
    out.push('');
    out.push(line(conv.summary));
    out.push('');
    out.push('| Area | Rule to follow | Evidence |');
    out.push('| --- | --- | --- |');
    for (const item of conv.conventions ?? []) {
      out.push(
        `| ${escCell(item.area)} | ${escCell(item.convention)} | ${(item.evidence ?? [])
          .map((f) => `\`${escCode(f)}\``)
          .join('<br>')} |`,
      );
    }
    out.push('');
    out.push('### Testing');
    out.push('');
    out.push(line(conv.testing));
    out.push('');
    if (conv.risks?.length) {
      out.push('## 6. Risk radar');
      out.push('');
      for (const risk of conv.risks) {
        out.push(
          `- **[${line(risk.severity).toUpperCase()}] ${line(risk.title)}** — ${line(
            risk.detail,
          )} _(${(risk.evidence ?? []).map((f) => `\`${escCode(f)}\``).join(', ')})_`,
        );
      }
      out.push('');
    }
  }

  const tasks = report.firstTasks;
  if (tasks) {
    out.push('## 7. Your first three contributions');
    out.push('');
    out.push(line(tasks.summary));
    out.push('');
    (tasks.tasks ?? []).forEach((task, index) => {
      out.push(`### ${index + 1}. ${line(task.title)} (${line(task.difficulty)})`);
      out.push('');
      out.push(`_${line(task.why)}_`);
      out.push('');
      if (task.files?.length) {
        out.push(`**Files:** ${task.files.map((f) => `\`${escCode(f)}\``).join(', ')}`);
        out.push('');
      }
      out.push('**Steps**');
      out.push('');
      out.push((task.steps ?? []).map((step, i) => `${i + 1}. ${line(step)}`).join('\n'));
      out.push('');
      out.push('**Done when**');
      out.push('');
      out.push(bullets(task.done ?? []));
      out.push('');
    });
  }

  const plan = report.onboarding;
  if (plan) {
    out.push('## 8. Ramp-up plan');
    out.push('');
    out.push(line(plan.summary));
    out.push('');
    for (const step of plan.steps ?? []) {
      out.push(`### ${line(step.day)} — ${line(step.title)}`);
      out.push('');
      out.push(`**Goal:** ${line(step.goal)}`);
      out.push('');
      out.push('**Do this**');
      out.push('');
      out.push(bullets(step.actions ?? []));
      out.push('');
      out.push(`**Checkpoint:** ${line(step.checkpoint)}`);
      if (step.files?.length) {
        out.push('');
        out.push(`**Files:** ${step.files.map((f) => `\`${escCode(f)}\``).join(', ')}`);
      }
      out.push('');
    }
    if (plan.questionsToAsk?.length) {
      out.push('## 9. Questions only your team can answer');
      out.push('');
      out.push(bullets(plan.questionsToAsk));
      out.push('');
    }
    if (plan.glossary?.length) {
      out.push('## 10. Glossary');
      out.push('');
      out.push('| Term | Meaning |');
      out.push('| --- | --- |');
      for (const term of plan.glossary) {
        out.push(`| ${escCell(term.term)} | ${escCell(term.meaning)} |`);
      }
      out.push('');
    }
  }

  // Evidence index
  const cited = new Map<string, Set<string>>();
  const addEvidence = (path: string, where: string) => {
    const clean = line(path);
    if (!clean) return;
    if (!cited.has(clean)) cited.set(clean, new Set());
    cited.get(clean)!.add(where);
  };
  arch?.evidence?.forEach((e) => addEvidence(e.path, 'architecture'));
  entries?.evidence?.forEach((e) => addEvidence(e.path, 'entry points'));
  conv?.evidence?.forEach((e) => addEvidence(e.path, 'conventions'));
  tasks?.evidence?.forEach((e) => addEvidence(e.path, 'first tasks'));
  plan?.evidence?.forEach((e) => addEvidence(e.path, 'ramp-up plan'));

  if (cited.size) {
    out.push('## 11. Evidence index');
    out.push('');
    out.push('Every file this report was built from, and where it was used.');
    out.push('');
    out.push('| File | Used in |');
    out.push('| --- | --- |');
    for (const [path, where] of [...cited.entries()].sort()) {
      out.push(`| \`${escCode(path)}\` | ${escCell([...where].join(', '))} |`);
    }
    out.push('');
  }

  if (stats) {
    out.push('## 12. Impact estimate');
    out.push('');
    out.push('| Metric | Value |');
    out.push('| --- | --- |');
    out.push(`| Tracked files in repository | ${stats.filesInRepo} |`);
    out.push(`| Files read by OnboardPilot | ${stats.filesRead} |`);
    out.push(`| Context characters processed | ${stats.charsRead} |`);
    out.push(`| Documentation files found | ${stats.docsFound} |`);
    out.push(`| Test files found | ${stats.testFiles} |`);
    out.push(`| Estimated manual ramp-up (heuristic) | ~${stats.estimatedManualHours} hours |`);
    out.push(`| OnboardPilot analysis time | under 1 minute |`);
    out.push('');
    out.push(
      '_The manual ramp-up figure is a heuristic derived from repository size and module count, not a measured benchmark._',
    );
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(
    'Built with **IBM Bob 2.0** for the IBM Bob 2.0 Hackathon. OnboardPilot is an AI workflow tool; treat its output as a starting map, not as ground truth.',
  );
  out.push('');

  return out.join('\n');
}
